=== RaphaelScursoni/Treinando-XML/livraria.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT livros (livro+)>
<!ATTLIST livro ISBN CDATA #REQUIRED>
<!ELEMENT livro (titulo, preco, autor*, idioma, editora, evento*, revisor)>
<!ATTLIST autor tipo (Principal|Tradutor) "Principal" >
<!ATTLIST evento data CDATA #REQUIRED>
<!ELEMENT revisor (nome, email, estado, tipo)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT editora (#PCDATA)>
<!ELEMENT evento (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

=== RaphaelScursoni/Treinando-XML/livraria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE livros SYSTEM "livraria.dtd">
<livros>
    <livro ISBN="9788175257665">
        <titulo>Harry Potter</titulo>
        <preco>49,99</preco>
        <autor tipo="Principal">J.K.Rowling</autor>
        <idioma>Português</idioma>
        <editora>Saraiva</editora>
        <evento fata="2020-01-08">Lançamento em Londres</evento>
        <revisor>
            <nome>Alberto Silva</nome>
            <email>alberto@uol.com.br</email>
            <estado>SP</estado>
            <tipo>2</tipo>
        </revisor>
    </livro>
</livros>
